### ISSUE TITLE
`torchao/_models/llama/eval.py` does not work with latest `lm_eval`

### ISSUE THREAD

**Issue by gau-nernst** [pytorch/ao#404] opened 2024-06-19 03:48 UTC
Using lm_eval==0.4.2, I'm getting this error

```
Traceback (most recent call last):
  File "/home/---/code/ao/torchao/_models/llama/eval.py", line 128, in <module>
    run_evaluation(
  File "/home/---/code/ao/torchao/_models/llama/eval.py", line 100, in run_evaluation
    TransformerEvalWrapper(
  File "/home/---/code/ao/torchao/_models/_eval.py", line 188, in __init__
    super().__init__(None, None)
  File "/home/---/code/ao/torchao/_models/_eval.py", line 55, in __init__
    super().__init__()
TypeError: HFLM.__init__() missing 1 required positional argument: 'pretrained'
```

Installing v0.4.0 fixed the error

```
pip install git+https://github.com/EleutherAI/lm-evaluation-harness@v0.4.0
```

Maybe we should pin lm_eval version? Since this is for internal testing only, just mention the specific version in the script is probably ok (or pin in `dev-requirements.txt`)

@HDCharles

**Comment by msaroufim** [comment] 2024-06-19 04:00
Can we just have some sanity test for this in CI?

**Comment by HDCharles** [comment] 2024-06-21 14:09
> Can we just have some sanity test for this in CI?

the issue is we don't have a good way to get access to the llama weights in CI

**Comment by HDCharles** [comment] 2024-06-21 22:05
see https://github.com/pytorch/ao/pull/414

**Comment by supriyar** [comment] 2024-06-21 23:03
@gau-nernst @HDCharles can we close this?

**Closed** 2024-06-21 23:27 UTC
