### ISSUE TITLE
How to trigger torchao unit tests?

### ISSUE THREAD

**Issue by goldhuang** [pytorch/ao#1315] opened 2024-11-19 22:50 UTC
We plan to run unit tests when we switch to different torch versions and triton versions.
How should we leverage with torchao's unit tests to make sure new torch version and triton versions are working?
Thanks!

**Comment by jerryzh168** [comment] 2024-11-19 22:56
depends on what test you want to run, but you can start with `python test/integration/test_integration.py`

**Comment by goldhuang** [comment] 2024-11-19 22:58
We want to test both the accuracy and functionality. It's better to run all the existing tests in this repo.
Should I just run tests under test folder one by one? It's not mentioned in readme file. So I want to check with you guys how you run the unit tests locally to be confident on new commits.

**Comment by jerryzh168** [comment] 2024-11-19 23:03
I see, maybe you can use pytest: https://github.com/pytorch/ao/blob/b714026478d87a98796498a9daf4edbb24845dca/.github/workflows/regression_test.yml#L107

**Comment by jerryzh168** [comment] 2024-12-05 01:43
closing since this seems to be resolved

**Closed by jerryzh168** 2024-12-05 01:43 UTC
