### ISSUE TITLE
2 sparse tests failing on main nightly job

### ISSUE THREAD

**Issue by msaroufim** [pytorch/ao#1158] opened 2024-10-24 01:54 UTC
https://github.com/pytorch/ao/actions/runs/11488769819/job/31976208709

```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
  =========================== short test summary info ============================
  FAILED test/prototype/test_sparse_api.py::TestQuantSemiSparse::test_quant_semi_sparse_compile_True - AssertionError: Tensor-likes are not close!
  
  Mismatched elements: 16384 / 16384 (100.0%)
  Greatest absolute difference: inf at index (0, 0) (up to 0.01 allowed)
  Greatest relative difference: nan at index (0, 0) (up to 0.01 allowed)
  
  To execute this test, run the following from the base repo dir:
      python test/prototype/test_sparse_api.py TestQuantSemiSparse.test_quant_semi_sparse_compile_True
  
  This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
  FAILED test/sparsity/test_fast_sparse_training.py::TestRuntimeSemiStructuredSparsity::test_runtime_weight_sparsification_compile - torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in function linear>(*(FakeTensor(..., device='cuda:0', size=(128, 256), grad_fn=<ReluBackward0>), SparseSemiStructuredTensorCUSPARSELT(shape=torch.Size([128, 256])), None), **{}):
  torch.float32
  
  from user code:
     File "/pytorch/ao/test/sparsity/test_fast_sparse_training.py", line 26, in forward
      x = self.linear2(x)
    File "/opt/conda/envs/venv/lib/python3.9/site-packages/torchao/sparsity/training/__init__.py", line 31, in forward
      return torch.nn.functional.linear(x, sparse_weight, self.bias)
  
  Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
  
  
  You can suppress this exception and fall back to eager by setting:
      import torch._dynamo
      torch._dynamo.config.suppress_errors = True
  
  
  To execute this test, run the following from the base repo dir:
      python test/sparsity/test_fast_sparse_training.py TestRuntimeSemiStructuredSparsity.test_runtime_weight_sparsification_compile
  
  This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
  ==== 2 failed, 1763 passed, 381 skipped, 131 warnings in 3358.25s (0:55:58) ====
  Error: Process completed with exit code 1.
```

**Comment by jcaip** [comment] 2024-10-24 17:26
cc @andrewor14 @jerryzh168 

So I think this is failing from the PR I merged in https://github.com/pytorch/pytorch/pull/137427 because of Tensor kwargs not being handled properly by the inductor lowering. 

It looks like the alpha vector gets mapped to bias, which is the cause of the numerical problems. 

I'm going to revert #137427, and add in the changes in https://github.com/pytorch/pytorch/pull/138703, which should fix this. 

In the meantime to fix in AO I'm planning to pin a torch version - lmk if this will break your workflow

**Closed** 2024-10-24 19:46 UTC
Labels: ci, high-priority, sparsity
